module.exports = {
    AddReactions: "Tepki Ekle",
    Administrator: "Yönetici",
    AttachFiles: "Dosyaları Ekle",
    BanMembers: "Üyeleri Yasakla",
    ChangeNickname: "Kullanıcı Adı değiştir",
  Connect: "Bağlan",
    CreateInstantInvite: "Anında Davet Oluştur",
    CreatePrivateThreads: "Özel Alt Başlık Oluştur",
    CreatePublicThreads: "Herkese Açık Alt Başlık Oluştur",
  DeafenMembers: "Üyeleri Sağırlaştır",
  EmbedLinks: "Gömülü Bağlantılar",
  KickMembers: "Üyeleri At",
  ManageChannels: "Kanalları Yönet",
  ManageEmojisAndStickers: "Sticker ve Emojileri Yönet",
  ManageEvents: "Etkinlikleri Yönet",
  ManageGuild: "Sunucuyu Yönet",
  ManageMessages: "Mesajları Yönet",
  ManageNicknames: "Kullanıcı Adlarını Yönet",
  ManageRoles: "Rolleri Yönet",
  ManageThreads: "Alt Başlıkları Yönet",
  ManageWebhooks: "Webhookları Yönet",
  MentionEveryone: "@everyone Etiketle",
    ModerateMembers: "Üyeleri Denetle",
  MoveMembers: "Üyeleri Taşı",
  MuteMembers: "Üyeleri Sustur",
  PrioritySpeaker: "Öncelikli Konuşmacı",
  ReadMessageHistory: "Mesaj Geçmişini Oku",
  RequestToSpeak: "Konuşmak İçin İstek Yolla",
  SendMessages: "Mesaj Gönder",
  SendMessagesInThreads: "Alt Başlıklara Mesaj Gönder",
  SendTTSMessages: "Sesli Mesaj Gönder",
  Speak: "Konuş",
  Stream: "Video",
  UseApplicationCommands: "Uygulama Komutlarını Kullan",
  UseEmbeddedActivities: "Aktiviteleri Kullan",
  UseExternalEmojis: "Dış Sunucudan Emoji Kullan",
  UseExternalStickers: "Dış Sunucudan Sticker Kullan",
    UseVAD: "Ses Etkinliğini Kullan",
  ViewAuditLog: "Denetim Kaydına Eriş",
  ViewChannel: "Kanalları Gör",
    ViewGuildInsights: "Sunucu İçgörülerini Görüntüle",
};
